name: aprentia
description: "Aprentia, a playful AI prompting practice app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/practice_items.json
    - assets/images/

